'use strict';
const fs=require('fs'), path=require('path'), os=require('os'), crypto=require('crypto');
const {spawnSync}=require('child_process');
function err(e){return e?{name:redact(String(e.name||'Error')).slice(0,200),message:redact(String(e.message||e)).slice(0,4000),code:e.code==null?null:redact(String(e.code)).slice(0,200),stack:redact(String(e.stack||'')).slice(0,12000)}:null;}
function redact(s){return String(s??'').replace(/(api[_-]?key|token|secret|password|authorization|cookie|db[_-]?key)([\"'\s:=]+)([^\s\"',;}]+)/ig,'$1$2[REDACTED]').replace(/\b[A-Fa-f0-9]{48,}\b/g,'[REDACTED_HEX]').replace(/\beyJ[A-Za-z0-9._-]{20,}\b/g,'[REDACTED_TOKEN]').replace(/([A-Za-z]:[\\/]+Users[\\/]+)[^\\/\r\n]+/ig,'$1[REDACTED_USER]').replace(/(\/home\/)[^/\r\n]+/g,'$1[REDACTED_USER]').slice(0,20000);}
function clean(v,d=0){if(d>5)return '[depth-limit]';if(v==null||typeof v==='boolean'||typeof v==='number')return v;if(typeof v==='string')return redact(v);if(v instanceof Error)return err(v);if(Array.isArray(v))return v.slice(0,100).map(x=>clean(x,d+1));if(typeof v==='object'){const o={};for(const [k,x] of Object.entries(v).slice(0,100))o[k]=/password|token|secret|cookie|authorization|dbkey|keyhex/i.test(k)?'[REDACTED]':clean(x,d+1);return o;}return redact(v);}
class FullDiagnostics{
 constructor(app){this.app=app;this.remoteReporter=null;this.boot=`${Date.now().toString(36)}-${crypto.randomBytes(3).toString('hex')}`;this.started=new Date().toISOString();this.dir=path.join(app.getPath('userData'),'diagnostics',`run-${this.started.replace(/[:.]/g,'-')}-${this.boot}`);fs.mkdirSync(this.dir,{recursive:true,mode:0o700});this.timeline=path.join(this.dir,'timeline.jsonl');this.errorsFile=path.join(this.dir,'errors.log');this.report=path.join(this.dir,'RELATORIO.txt');this.seq=0;this.stages=[];this.errors=[];}
 event(event,details={}){const x={at:new Date().toISOString(),seq:++this.seq,boot:this.boot,event:String(event),details:clean(details)};try{fs.appendFileSync(this.timeline,JSON.stringify(x)+'\n',{encoding:'utf8',mode:0o600});}catch(_){}return x;}
 stage(name,status='OK',details={}){this.stages.push({at:new Date().toISOString(),name:String(name),status:String(status),details:clean(details)});this.event('stage.'+String(name).replace(/\s+/g,'-').toLowerCase(),{status,...details});this.writeReport();}
 setRemoteReporter(reporter){this.remoteReporter=reporter||null;}
 error(source,e,details={}){try{this.remoteReporter?.captureException?.(e,{source:String(source),details:clean(details)});}catch(_){}const x={at:new Date().toISOString(),source:String(source),error:err(e),details:clean(details)};this.errors.push(x);this.event('error',x);try{fs.appendFileSync(this.errorsFile,JSON.stringify(x,null,2)+'\n','utf8');}catch(_){}this.writeReport();}
 system(){const x={platform:process.platform,arch:process.arch,node:process.version,electron:process.versions.electron,chromium:process.versions.chrome,appVersion:this.app.getVersion(),packaged:this.app.isPackaged,execPath:process.execPath,resourcesPath:process.resourcesPath,userData:this.app.getPath('userData'),appData:this.app.getPath('appData'),temp:this.app.getPath('temp'),env:{LOCALAPPDATA:Boolean(process.env.LOCALAPPDATA),PROGRAMFILES:Boolean(process.env.PROGRAMFILES),PROGRAMFILES_X86:Boolean(process.env['PROGRAMFILES(X86)'])},os:{type:os.type(),release:os.release(),version:os.version?.(),totalmem:os.totalmem(),freemem:os.freemem(),cpuModels:[...new Set(os.cpus().map(c=>c.model))]}};try{fs.writeFileSync(path.join(this.dir,'system.json'),JSON.stringify(clean(x),null,2),'utf8');}catch(_){}this.event('system.snapshot',x);}
 processes(){if(process.platform!=='win32')return;try{const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',"Get-CimInstance Win32_Process | Where-Object {$_.Name -match 'Vyzium|chrome|msedge|powershell|followup|compras'} | Select-Object Name,ProcessId,ParentProcessId,ExecutablePath | ConvertTo-Json -Compress"],{encoding:'utf8',windowsHide:true,timeout:8000});fs.writeFileSync(path.join(this.dir,'processes.json'),redact(r.stdout||'[]')||'[]','utf8');this.event('process.snapshot',{exitCode:r.status,stderr:redact(r.stderr||'')});}catch(e){this.error('process.snapshot',e);}}
 writeReport(){const a=['VYZIUM - RELATORIO DE DIAGNOSTICO INTEGRAL',`Versao: ${this.app.getVersion()}`,`Inicio: ${this.started}`,`Boot: ${this.boot}`,'','LINHA DO TEMPO RESUMIDA'];for(const x of this.stages)a.push(`[${x.status}] ${x.at} - ${x.name}${Object.keys(x.details||{}).length?' | '+redact(JSON.stringify(x.details)):''}`);a.push('',`ERROS CAPTURADOS: ${this.errors.length}`);for(const x of this.errors.slice(-30))a.push(`[ERRO] ${x.at} ${x.source}: ${x.error?.message||'sem mensagem'}`);a.push('','Detalhes: timeline.jsonl, system.json, processes.json, errors.log, hidden-browser.log e whatsapp-debug.jsonl.');try{fs.writeFileSync(this.report,a.join('\r\n'),'utf8');}catch(_){}}
 copy(source,name){try{if(source&&fs.existsSync(source))fs.copyFileSync(source,path.join(this.dir,name));}catch(e){this.error('diagnostics.copy',e,{name});}}
 bundle(){if(process.platform!=='win32')return null;try{const out=path.join(path.dirname(this.dir),`Vyzium-Diagnostico-${this.boot}.zip`);const esc=x=>String(x).replace(/'/g,"''");const cmd=`Compress-Archive -LiteralPath '${esc(this.dir)}\\*' -DestinationPath '${esc(out)}' -Force`;const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',cmd],{encoding:'utf8',windowsHide:true,timeout:30000});this.event('diagnostics.bundle',{output:out,exitCode:r.status,stderr:redact(r.stderr||'')});return r.status===0?out:null;}catch(e){this.error('diagnostics.bundle',e);return null;}}
 finalize(extra={}){this.event('diagnostics.finalize',extra);this.processes();this.writeReport();return this.bundle();}
}
module.exports={FullDiagnostics,clean,redact};
